### ISSUE TITLE
Negative w parameter

### ISSUE THREAD

**Issue by philipphoehn** [MarkusPic/intensity_duration_frequency_analysis#3]
Dear Markus,

a relatively short time series behaved as expected in testing purposes. However, I have noticed that w takes on negative sign and hinders further computations depending on log10 when elongating the time series. Do you have any hints on how this might (perhaps mathematically) occur or what this could imply?

I find your package great and unique, would really love to experiment with it without having to implement it myself at the moment, and thus hope for your thoughts.

Best
Philipp

**Comment by MarkusPic** [comment]
Dear Philipp

I couldn't find any problems in the code. Would you send me the data you used? (markus.pichler@tugraz.at) A negative w should not be possible.

Best
Markus
