### ISSUE TITLE
Suggest adding the introduction of fitting function

### ISSUE THREAD

**Issue by babybearming** [MarkusPic/intensity_duration_frequency_analysis#7]
Which function did the author use to make the IDF curve, the GEV distribution?

**Comment by MarkusPic** [comment]
Hi, i added a pseudo-code of the basic functionality of the analysis in the [readme](https://github.com/MarkusPic/intensity_duration_frequency_analysis#background). Dose this answer your question?

**Comment by babybearming** [comment]
Yes, I found the relevant answer from the pseudo-code you provided，thank you.
