### ISSUE TITLE
Which changes allow to run properly the model with input that are different from N-Tagensummen

### ISSUE THREAD

**Issue by Simone1085** [MarkusPic/intensity_duration_frequency_analysis#9]
**I am not able to obtain properly result with precipitation series different from 1 N-Minutensummen**
I am trying to use your code to obtain IDF of a weather stations that does not belong to Austrian network. In your example you use precipitation every minute, but I don't understand from your documentation if your model only works for a dataset with records precipitation every minute or if the model run well even with longer time interval. 

**IDF with input series based on 1 day (see attachment Stabio.csv**)
I would like to use as input a series with the DAILY precipitation 
[Stabio.csv](https://github.com/user-attachments/files/16927521/Stabio.csv
and obtain after a disaggregation a IDF with rain duration (5 min to 8640 min) and return period 1 to 100 years. I run the following code adapted from your model.   

```
from pathlib import Path
import os
from idf_analysis import IntensityDurationFrequencyAnalyse
from idf_analysis.definitions import *
import pandas as pd
import matplotlib.pyplot as plt
import datetime
output_directory = Path('ehyd_112086_idf_data')
df=pd.read_csv("P:\Progetto_pyCharm\intensity_duration_frequency_analysis\examples\ehyd_112086_idf_data/Stabio.csv", sep=";")
#necessary to rename column to work with to_datetime
a=df.rename(columns={"JAHR": "year", "MO": "month", "TG": "day", "HH":"hour", "MM":"minute"})
print(a)

a['datetime'] = pd.to_datetime(a[['year', 'month', 'day', 'hour', 'minute']])

a['datetime'] = a['datetime'].dt.strftime('%Y-%m-%d %H:%M:%S')
a['datetime']= pd.to_datetime(a['datetime'])

c=a.drop(['year', 'month', "day", "hour", "minute"], axis=1)
print(c.info())


# initialize of the analysis class
idf = IntensityDurationFrequencyAnalyse(series_kind=SERIES.PARTIAL, worksheet=METHOD.KOSTRA, extended_durations=True)
series = pd.Series(data=c['precipitazioni'].values, index=c['datetime'])
#print(type(series))
idf.set_series(series)
# auto-save the calculated parameter so save time for a later use, as the parameters doesn't have to be calculated again.
idf.auto_save_parameters(output_directory / 'idf_parameters_new.yaml')

idf.model_rain_euler.get_series(return_period=.5, duration=60)

# exit()

# idf.result_figure(color=False)

# --------
# plotting the IDF curves
fig, ax = idf.result_figure(color=True)
fig.set_size_inches(12, 8)
fig.set_layout_engine('constrained')
fig.savefig(output_directory / 'idf_curves_plot_color.png', dpi=200)
plt.close(fig)

# -------
# plotting the idf curves in black and white
fig, ax = idf.result_figure(color=False, add_interim=True)
fig.set_size_inches(12, 8)
fig.set_layout_engine('constrained')
fig.savefig(output_directory / 'idf_curves_plot.png', dpi=200)
plt.close(fig)

# save the values of the idf curve as csv file
idf.result_table(add_names=False).to_csv(output_directory / 'idf_table_UNIX.csv',
                                         sep=',', decimal='.', float_format='%0.2f')
```

It generates a warning "P:\Progetto_pyCharm\intensity_duration_frequency_analysis\idf_analysis\synthetic_rainseries.py:125: UserWarning: The precipitation depth does not increase with the duration step. -> Adjusting data.
  warnings.warn('The precipitation depth does not increase with the duration step. -> Adjusting data.')" and the result does not make sense. 
[idf_table_UNIX.csv](https://github.com/user-attachments/files/16926402/idf_table_UNIX.csv)

**Question:** how should I have to change the code to allow model running with 1 day time interval (1440 minutes or other) series of precipitation? More in general, how should I have to change the code for different time interval series. At the moment I am able to obtain properly results only with 1 minute time rain interval used in your example with N-Minutensummen.csv .  At the moment, I assume that the result is wrong because the code does not have information about time interval and it runs as the time interval is 1 minute. You should tell me how to tell the model that the data are 1 day or even 10 minutes and allow it to disaggregate. Or does not disaggregate the model and you have to disaggregate BEFORE using the model (a preprocessing of your input that transform daily series in minutensummen)? 
It could be useful to add a sample code in your examples folder to allow users to see how to manage the issue or info in your documentation.

**Comment by MarkusPic** [comment]
Hi, 

Thank you for providing the data; this makes the error analysis much easier.

Firstly, you cannot obtain statistical values for durations that are smaller than the measurement interval of the precipitation time series.

Additionally, the package can handle different intervals, but the series should maintain a consistent and equidistant interval.

The reason for the unrealistic values is the presence of erroneous data in your time series:

```
2009-01-26    32767.0
2009-01-27    32767.0
2009-01-28    32767.0
2009-01-29    32767.0
2012-05-06    32767.0
2012-05-07    32767.0
2013-10-30    32767.0
2013-10-31    32767.0
```

I hope this helps! If you have any further questions, please feel free to reach out—I’m happy to assist.

Regards,
Markus

**Comment by Simone1085** [comment]
> Hi,
> 
> Thank you for providing the data; this makes the error analysis much easier.
> 
> Firstly, you cannot obtain statistical values for durations that are smaller than the measurement interval of the precipitation time series.
> 
> Additionally, the package can handle different intervals, but the series should maintain a consistent and equidistant interval.
> 
> The reason for the unrealistic values is the presence of erroneous data in your time series:
> 
> ```
> 2009-01-26    32767.0
> 2009-01-27    32767.0
> 2009-01-28    32767.0
> 2009-01-29    32767.0
> 2012-05-06    32767.0
> 2012-05-07    32767.0
> 2013-10-30    32767.0
> 2013-10-31    32767.0
> ```
> 
> I hope this helps! If you have any further questions, please feel free to reach out—I’m happy to assist.
> 
> Regards, Markus

Thank you for your answer. 

The series now stops to 31.12.2008 and therefore 32767 are disappeared, nevertheless the result has not changed and the unrealistic values remain. Furthermore I have even changed duration to 1440 (1 day).

Here the new input dataset for series:
[Stabio.csv](https://github.com/user-attachments/files/16946034/Stabio.csv)

**Comment by Simone1085** [comment]
> If I understand correctly, you are referring to this line of code:
> 
> `idf.model_rain_euler.get_series(return_period=.5, duration=1440)`
> 
> What this makes is a design rainfall hyetograph with a duration of 1440 minutes = 1 day. The precipitation is formulated to ensure that, across all duration intervals up to the defined event duration, the specified return period is maximized. The peak intensity occurs one-third into the duration.
> 
> The shortest interval you can make is the same interval as your precipitation series, meaning for your data 1 day. But in your code, the default interval is used, since you didn't change it with the argument `interval`.
> 
> So a functioning Euler rain series would be, for example:
> 
> `idf.model_rain_euler.get_series(return_period=.5, duration=1440*7, interval=1440)`

Thank you for the answer. 

You've understood correctly. 

the key issue was this
`idf.model_rain_euler.get_series(return_period=.5, duration=1440)`

I've changed as you suggested: 
`idf.model_rain_euler.get_series(return_period=.5, duration=1440*7, interval=1440)`

I confirm that now the problem have disappeared!

The problem is that for the other two Args: duration, kind
I verified that you defined in synthetic_rainseries.py the function get_series and you described in that way:

```
 @staticmethod
    def _get_occurrence_highest_intensity(kind=2):
        if kind == 1:
            return 0
        elif kind == 2:
            return 1 / 3

    def get_series(self, return_period, duration, interval=5, kind=2, **kwargs):
        """
        Get a pandas.Series of the model euler rain with the passed minutes as integer-index.

        Args:
            return_period (int or float): Return period in years.
            duration (int): Duration step in minutes.
            interval (int): Series intervall in minutes.
            kind (int): Either type I (1) or type II (2)
            **kwargs: Other key word arguments for subclasses.

        Returns:
            pd.Series: series of the model rain.
        """
```

I guess: 
-duration (int) is the time that the rain lasts. If I have a rain with duration 8 minutes and with a 5 min interval series will be calculated as 10 minute long, the same rain duration with a 2 min interval will be calculated as 8 minutes long. **Do you confirm?**
-kind is how the reain peak is calculated, because two days ago do you tell me "The peak intensity occurs one-third into the duration" and I see:
```
 elif kind == 2:
            return 1 / 3
```
But when kind == 1? 
```
        if kind == 1:
            return 0
```
**Does it mean that the rain intensity reachs the peak suddenly like a like a bucket of water from the sky? Why do you assume this unrealistic behavior? Ok, it is not default in def get_series, but it seems me strange to give the possibility to allow to use in the function...**

Thank you again for your time

**Comment by MarkusPic** [comment]
As for the duration. I recommend that you use a duration that is a multiple of the interval, but yes, the described scenarios are correct.

The Euler model rain is first mentioned in 1981 and highly used in German-speaking countries. The creator (Euler) defined three types of rain, where the peak intensity is at the beginning, after one third and after 40% of the duration.

**Comment by MarkusPic** [comment]
I also tried to find a publication, but I only have this information from:

> Verworn, H.-R. (1999). Die Anwendung von Kanalnetzmodellen in der Stadthydrologie. Universität Hannover.
 
... where he states on page 59:

> Die Modellregen nach EULER (1981) (dargestellt in ALTHAUS (1985)) werden aus örtlich gültigen
Regenhöhenlinien nach folgenden Grundsätzen abgeleitet ...

... and quotes:

> Althaus, J. (1985) : Vergleich von Modellregen zur Kanalnetzberechnung. Mitt. Inst. f. Wasserwirtschaft, Hydrologie und landwirtschaftl. Wasserbau, Universität Hannover, Heft 56

**Comment by dimfalk** [comment]
Thanks, that's a great starting point. I'll get back to you as soon as I find the sources.
